<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>sa.informatix.tools</groupId>
  <artifactId>lab04</artifactId>
  <version>1.0-SNAPSHOT</version>

  <name>MyProject Name</name>
  <description>
    This project is a Maven-based JavaFX project,
    including generating a project documentation website with the Maven Site plugin.
  </description>
  <url>https://se411-lab04.com</url>

  <licenses>
    <license>
      <name>Apache License 2.0</name>
      <url>https://www.apache.org/licenses/LICENSE-2.0</url>
    </license>
  </licenses>

  <organization>
    <name>SE411-Tech-Company</name>
    <url>https://mycompanyUrl.dom</url>
  </organization>

  <developers>
    <developer>
      <name>Hamzah Alyamani</name>
      <email>222110595@psu.edu.sa</email>
    </developer>
  </developers>

  <dependencies>
    <dependency>
      <groupId>org.openjfx</groupId>
      <artifactId>javafx-controls</artifactId>
      <version>23</version>
    </dependency>

  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.openjfx</groupId>
        <artifactId>javafx-maven-plugin</artifactId>
        <version>0.0.8</version>
        <configuration>
          <mainClass>sa.informatix.tools.App</mainClass>
        </configuration>
      </plugin>
    </plugins>
  </build>

</project>
